periodics:
  - interval: 12h
    name: periodic-kueue-test-unit-s390x-ppc64le-main
    cluster: eks-prow-build-cluster
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: periodic-kueue-test-unit-s390x-ppc64le-main
      testgrid-alert-email: kueue-alerts@kubernetes.io
      testgrid-num-failures-to-alert: '1'
      description: "Run s390x periodic kueue unit tests"
      testgrid-num-columns-recent: '30'
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    extra_refs:
      - org: kubernetes-sigs
        repo: kueue
        base_ref: main
        path_alias: kubernetes-sigs/kueue
    decorate: true
    decoration_config:
      timeout: 1h
    spec:
      containers:
       containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20250527-1b2b10e804-master
          env:
            - name: E2E_K8S_VERSION
              value: "1.30"
            - name: BUILDER_IMAGE
              value: public.ecr.aws/docker/library/golang:1.24
          command:
            # generic runner script, handles DIND, bazelrc for caching, etc.
            - runner.sh
          args:
            - make
            - image-build
            - PLATFORMS=linux/s390x,linux/ppc64le
          # docker-in-docker needs privileged mode
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: "4"
              memory: "6Gi"
            limits:
              cpu: "4"
              memory: "6Gi"
