presubmits:
  kubernetes/kubernetes:
  - name: pull-kubernetes-e2e-capz-windows-1-29
    cluster: eks-prow-build-cluster
    always_run: false
    branches:
    - release-1.29
    decorate: true
    extra_refs:
    - base_ref: release-1.16
      org: kubernetes-sigs
      path_alias: sigs.k8s.io/cluster-api-provider-azure
      repo: cluster-api-provider-azure
      workdir: false
    - base_ref: master
      org: kubernetes-sigs
      path_alias: sigs.k8s.io/cloud-provider-azure
      repo: cloud-provider-azure
    - org: kubernetes-sigs
      repo: windows-testing
      base_ref: master
      path_alias: k8s.io/windows-testing
      workdir: true
    labels:
      preset-azure-community: "true"
      preset-capz-containerd-1-7-latest: "true"
      preset-capz-windows-2022: "true"
      preset-capz-windows-common-pull: "true"
      preset-dind-enabled: "true"
    optional: true
    path_alias: k8s.io/kubernetes
    run_if_changed: azure.*\.go$|.*windows\.go$|test/e2e/windows/.*
    spec:
      serviceAccountName: azure
      containers:
      - command:
        - "runner.sh"
        - "env"
        - "./capz/run-capz-e2e.sh"
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20250227-3a13bdd784-1.29
        name: ""
        resources:
          requests:
            cpu: "2"
            memory: 9Gi
          limits:
            cpu: "2"
            memory: 9Gi
        env:
          - name: GINKGO_SKIP
            value: \[LinuxOnly\]|\[Serial\]|\[Slow\]|\[Excluded:WindowsDocker\]|\[Feature:DynamicResourceAllocation\]|Networking.Granular.Checks(.*)node-pod.communication|Guestbook.application.should.create.and.stop.a.working.application|device.plugin.for.Windows|Container.Lifecycle.Hook.when.create.a.pod.with.lifecycle.hook.should.execute(.*)http.hook.properly|\[sig-api-machinery\].Garbage.collector|pull.from.private.registry.with.secret
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: sig-windows-presubmit
      testgrid-tab-name: pull-kubernetes-e2e-capz-windows-1-29
      testgrid-num-columns-recent: '30'
