presubmits:
  kubernetes-sigs/azuredisk-csi-driver:
  - name: pull-azuredisk-csi-driver-verify
    cluster: k8s-infra-prow-build
    decorate: true
    always_run: true
    path_alias: sigs.k8s.io/azuredisk-csi-driver
    branches:
    - (master)|(^release-.+$)
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240803-cf1183f2db-master
        command:
        - runner.sh
        args:
        - make
        - verify
        resources:
          limits:
            cpu: 4
            memory: 8Gi
          requests:
            cpu: 4
            memory: 8Gi
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: provider-azure-azuredisk-csi-driver
      testgrid-tab-name: pr-azuredisk-csi-driver-verify
      description: "Run code verification tests for Azure Disk CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-azuredisk-csi-driver-unit
    cluster: k8s-infra-prow-build
    decorate: true
    skip_if_only_changed: "^docs/|^site/|^\\.github/|\\.(md|adoc)$|^(README|LICENSE)$"
    path_alias: sigs.k8s.io/azuredisk-csi-driver
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240803-cf1183f2db-master
        command:
        - runner.sh
        args:
        - make
        - unit-test
        resources:
          limits:
            cpu: 4
            memory: 8Gi
          requests:
            cpu: 4
            memory: 8Gi
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: provider-azure-azuredisk-csi-driver
      testgrid-tab-name: pr-azuredisk-csi-driver-unit
      description: "Run unit tests for Azure Disk CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-azuredisk-csi-driver-windows-build
    cluster: k8s-infra-prow-build
    decorate: true
    skip_if_only_changed: "^docs/|^site/|^\\.github/|\\.(md|adoc)$|^(README|LICENSE)$"
    path_alias: sigs.k8s.io/azuredisk-csi-driver
    branches:
    - (master)|(^release-.+$)
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240803-cf1183f2db-master
        command:
        - runner.sh
        args:
        - make
        - azuredisk-windows
        resources:
          limits:
            cpu: 4
            memory: 8Gi
          requests:
            cpu: 4
            memory: 8Gi
    annotations:
      testgrid-dashboards: provider-azure-azuredisk-csi-driver
      testgrid-tab-name: pr-azuredisk-csi-driver-windows-build
      description: "Run make azuredisk-windows for Azure Disk CSI driver."
      testgrid-num-columns-recent: '30'
