periodics:
  - interval: 12h
    name: periodic-jobset-test-unit-release-0-8
    cluster: eks-prow-build-cluster
    extra_refs:
      - org: kubernetes-sigs
        repo: jobset
        base_ref: release-0.8
        path_alias: sigs.k8s.io/jobset
    annotations:
      testgrid-dashboards: sig-apps
      testgrid-tab-name: periodic-jobset-test-unit-release-0-8
      testgrid-num-failures-to-alert: '1'
      description: "Run periodic jobset unit tests"
      testgrid-num-columns-recent: '30'
    labels:
      preset-dind-enabled: "true"
    decorate: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20250227-3a13bdd784-master
        env:
        - name: GO_TEST_FLAGS
          value: "-race -count 3"
        command:
        # generic runner script, handles DIND, bazelrc for caching, etc.
        - runner.sh
        args:
        - make
        - test
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 3
            memory: 10Gi
          requests:
            cpu: 3
            memory: 10Gi
  - interval: 12h
    name: periodic-jobset-test-integration-release-0-8
    cluster: eks-prow-build-cluster
    extra_refs:
      - org: kubernetes-sigs
        repo: jobset
        base_ref: release-0.8
        path_alias: sigs.k8s.io/jobset
    annotations:
      testgrid-dashboards: sig-apps
      testgrid-tab-name: periodic-jobset-test-integration-release-0-8
      testgrid-num-failures-to-alert: '1'
      description: "Run periodic jobset integration tests for release 0.8"
      testgrid-num-columns-recent: '30'
    labels:
      preset-dind-enabled: "true"
    decorate: true
    spec:
      containers:
      - image: public.ecr.aws/docker/library/golang:1.23
        command:
        - make
        args:
        - test-integration
        resources:
          limits:
            cpu: 3
            memory: 10Gi
          requests:
            cpu: 3
            memory: 10Gi
