dashboards:
- dashboard_tab:
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-openshift-cluster-nfd-operator-release-4.19-ocp4.19-lp-rosa-hypershift-nfd-e2e-master-aws-rosa-hypershift
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-openshift-cluster-nfd-operator-release-4.19-ocp4.19-lp-rosa-hypershift-nfd-e2e-master-aws-rosa-hypershift
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-openshift-logging-extended-logging-tests-interop-main-openshift-logging-hypershift-4.19-lp-rosa-hypershift-openshift-logging-aws-rosa-hypershift
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-openshift-logging-extended-logging-tests-interop-main-openshift-logging-hypershift-4.19-lp-rosa-hypershift-openshift-logging-aws-rosa-hypershift
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-openshift-pipelines-release-tests-release-v1.19-openshift-pipelines-ocp4.19-lp-rosa-hypershift-openshift-pipelines-aws-rosa-hypershift
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-openshift-pipelines-release-tests-release-v1.19-openshift-pipelines-ocp4.19-lp-rosa-hypershift-openshift-pipelines-aws-rosa-hypershift
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-openshift-pipelines-release-tests-release-v1.20-openshift-pipelines-ocp4.19-lp-rosa-hypershift-openshift-pipelines-aws-rosa-hypershift
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-openshift-pipelines-release-tests-release-v1.20-openshift-pipelines-ocp4.19-lp-rosa-hypershift-openshift-pipelines-aws-rosa-hypershift
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.19-lp-rosa-hypershift-devspaces-aws-rosa-hypershift
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.19-lp-rosa-hypershift-devspaces-aws-rosa-hypershift
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-rhbk-sso-test-main-rhsso-product-ocp4.19-lp-rosa-hypershift-rhsso-aws-rosa-hypershift
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-rhbk-sso-test-main-rhsso-product-ocp4.19-lp-rosa-hypershift-rhsso-aws-rosa-hypershift
  name: redhat-openshift-lp-rosa-hypershift-release-4.19-informing
test_groups:
- gcs_prefix: test-platform-results/logs/periodic-ci-openshift-cluster-nfd-operator-release-4.19-ocp4.19-lp-rosa-hypershift-nfd-e2e-master-aws-rosa-hypershift
  name: periodic-ci-openshift-cluster-nfd-operator-release-4.19-ocp4.19-lp-rosa-hypershift-nfd-e2e-master-aws-rosa-hypershift
- gcs_prefix: test-platform-results/logs/periodic-ci-openshift-logging-extended-logging-tests-interop-main-openshift-logging-hypershift-4.19-lp-rosa-hypershift-openshift-logging-aws-rosa-hypershift
  name: periodic-ci-openshift-logging-extended-logging-tests-interop-main-openshift-logging-hypershift-4.19-lp-rosa-hypershift-openshift-logging-aws-rosa-hypershift
- gcs_prefix: test-platform-results/logs/periodic-ci-openshift-pipelines-release-tests-release-v1.19-openshift-pipelines-ocp4.19-lp-rosa-hypershift-openshift-pipelines-aws-rosa-hypershift
  name: periodic-ci-openshift-pipelines-release-tests-release-v1.19-openshift-pipelines-ocp4.19-lp-rosa-hypershift-openshift-pipelines-aws-rosa-hypershift
- gcs_prefix: test-platform-results/logs/periodic-ci-openshift-pipelines-release-tests-release-v1.20-openshift-pipelines-ocp4.19-lp-rosa-hypershift-openshift-pipelines-aws-rosa-hypershift
  name: periodic-ci-openshift-pipelines-release-tests-release-v1.20-openshift-pipelines-ocp4.19-lp-rosa-hypershift-openshift-pipelines-aws-rosa-hypershift
- gcs_prefix: test-platform-results/logs/periodic-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.19-lp-rosa-hypershift-devspaces-aws-rosa-hypershift
  name: periodic-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.19-lp-rosa-hypershift-devspaces-aws-rosa-hypershift
- gcs_prefix: test-platform-results/logs/periodic-ci-rhbk-sso-test-main-rhsso-product-ocp4.19-lp-rosa-hypershift-rhsso-aws-rosa-hypershift
  name: periodic-ci-rhbk-sso-test-main-rhsso-product-ocp4.19-lp-rosa-hypershift-rhsso-aws-rosa-hypershift
