periodics:
  - name: ci-kubernetes-unit-ppc64le
    interval: 1h
    cluster: k8s-infra-ppc64le-prow-build
    decorate: true
    extra_refs:
      - org: kubernetes
        repo: kubernetes
        base_ref: master
        path_alias: k8s.io/kubernetes
    annotations:
      testgrid-dashboards: ibm-ppc64le-k8s, ibm-ppc64le-periodics
      testgrid-tab-name: ci-kubernetes-unit-ppc64le
    spec:
      # unit tests have no business requiring root or doing privileged operations
      securityContext:
        # NOTE: these are arbitrary non-root values. They don't exist in the
        # image and don't need to, the unit tests should only write to TMPDIR
        runAsGroup: 2010
        runAsUser: 2001
      containers:
        - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20250904-2613a23300-master
          command:
            - make
            - test
          env:
            - name: KUBE_TIMEOUT
              value: "-timeout=300s"
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 6
              memory: "28Gi"
            limits:
              cpu: 6
              memory: "28Gi"

  - name: ci-kubernetes-ppc64le-conformance-latest-kubetest2
    interval: 3h
    cluster: k8s-infra-ppc64le-prow-build
    labels:
      preset-ibmcloud-cred: "true"
    decorate: true
    decoration_config:
      timeout: 220m
    extra_refs:
      - base_ref: main
        org: kubernetes-sigs
        repo: provider-ibmcloud-test-infra
        workdir: true
    annotations:
      description: Runs conformance tests using kubetest2 against kubernetes ci latest on IBM powervs
      testgrid-dashboards: ibm-ppc64le-e2e, ibm-ppc64le-k8s, conformance-ppc64le, ibm-k8s-e2e
      testgrid-tab-name: ci-kubernetes-ppc64le-conformance-latest-kubetest2
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20250904-2613a23300-master
          securityContext:
            privileged: true
          env:
            - name: "BOSKOS_HOST"
              value: "boskos.test-pods.svc.cluster.local"
            - name: "USER"
              value: "ci-kubernetes-ppc64le-conformance-latest-kubetest2"
          resources:
            requests:
              cpu: 4
              memory: "14Gi"
            limits:
              cpu: 4
              memory: "14Gi"
          command:
            - runner.sh
          args:
            - bash
            - -c
            - |
              set -o xtrace

              #Call to boskos to checkout resource
              source "./hack/boskos.sh"

              #Setup of kubetest2 tf deployer and ginkgo tester
              make install-deployer-tf
              go install sigs.k8s.io/kubetest2/kubetest2-tester-ginkgo@latest

              CLUSTER_NAME="config1-$(date +%s)"

              set +o errexit
              set -o xtrace
              kubetest2 tf --powervs-image-name CentOS-Stream-10 --powervs-memory 32 \
                --powervs-region ${BOSKOS_REGION} --powervs-zone ${BOSKOS_ZONE} \
                --powervs-service-id ${BOSKOS_RESOURCE_ID} --powervs-ssh-key k8s-prow-sshkey \
                --ssh-private-key /etc/secret-volume/ssh-privatekey \
                --workers-count 2 --cluster-name $CLUSTER_NAME \
                --up --auto-approve --retry-on-tf-failure 3 \
                --break-kubetest-on-upfail true \
                --build-version $(curl -Ls https://dl.k8s.io/ci/latest.txt) \
                --test=ginkgo -- --parallel 10 --test-package-dir ci --test-package-marker latest.txt --focus-regex='\[Conformance\]' --skip-regex='\[Serial\]'; rc1=$?

              export KUBECONFIG="$(pwd)/$CLUSTER_NAME/kubeconfig"
              export ARTIFACTS=$ARTIFACTS/serial_tests_artifacts
              #Run Serial Conformance tests
              kubetest2 tf --powervs-region ${BOSKOS_REGION} --powervs-zone ${BOSKOS_ZONE} \
                --powervs-service-id ${BOSKOS_RESOURCE_ID} \
                --ignore-cluster-dir true \
                --cluster-name $CLUSTER_NAME \
                --down --auto-approve --ignore-destroy-errors \
                --test=ginkgo -- --test-package-dir ci --test-package-marker latest.txt --focus-regex='\[Serial\].*\[Conformance\]'; rc2=$?

              [ -z "${BOSKOS_HOST:-}" ] || release_account >> "$ARTIFACTS/boskos.log" 2>&1

              if [ $rc1 != 0 ]; then
                  echo "ERROR: Non Serial k8s Conformance tests exited with code: $rc1"
                  exit $rc1
              elif [ $rc2 != 0 ]; then
                  echo "ERROR: Serial k8s Conformance tests exited with code: $rc2"
                  exit $rc2
              fi
  - name: ci-kubernetes-ppc64le-e2e-node-latest-kubetest2
    interval: 6h
    cluster: k8s-infra-ppc64le-prow-build
    labels:
      preset-ibmcloud-cred: "true"
    decorate: true
    decoration_config:
      timeout: 220m
    extra_refs:
      - base_ref: main
        org: kubernetes-sigs
        repo: provider-ibmcloud-test-infra
        workdir: true
    annotations:
      description: Runs e2e-node tests using kubetest2 on IBM powervs
      testgrid-dashboards: ibm-ppc64le-node-e2e, ibm-ppc64le-k8s, sig-node-ppc64le
      testgrid-tab-name: ci-kubernetes-ppc64le-e2e-node-latest-kubetest2
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20250904-2613a23300-master
          env:
            - name: "BOSKOS_HOST"
              value: "boskos.test-pods.svc.cluster.local"
            - name: "USER"
              value: "ci-kubernetes-ppc64le-e2e-node-latest-kubetest2"
          resources:
            requests:
              cpu: 2
              memory: 10Gi
            limits:
              cpu: 2
              memory: 10Gi
          command:
            - runner.sh
          args:
            - bash
            - -c
            - |
              set -o xtrace

              source "./hack/boskos.sh"

              make install-deployer-tf

              CLUSTER_NAME="config2-$(date +%s)"

              set +o errexit
              kubetest2 tf --powervs-image-name CentOS-Stream-10 --powervs-memory 32 \
                --powervs-region ${BOSKOS_REGION} --powervs-zone ${BOSKOS_ZONE} \
                --powervs-service-id ${BOSKOS_RESOURCE_ID} --powervs-ssh-key k8s-prow-sshkey \
                --ssh-private-key /etc/secret-volume/ssh-privatekey \
                --cluster-name $CLUSTER_NAME \
                --up --set-kubeconfig=false --auto-approve --retry-on-tf-failure 3 \
                --build-version $(curl -Ls https://dl.k8s.io/ci/latest.txt) \
                --break-kubetest-on-upfail true \
                --playbook k8s-node-remote.yml

              EXTERNAL_IP=`grep -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' $(pwd)/$CLUSTER_NAME/hosts`

              # Skipping test related to https://github.com/kubernetes/kubernetes/issues/124791
              kubetest2 tf --test=exec -- ssh -i /etc/secret-volume/ssh-privatekey root@$EXTERNAL_IP \
                "export SKIP='\[Flaky\]|\[Slow\]|\[Serial\]|should.execute.readiness.probe.while.in.preStop' && /make-test-e2e-node.sh"; \
                rc=$?; scp -r -i /etc/secret-volume/ssh-privatekey root@$EXTERNAL_IP:/tmp/_artifacts $ARTIFACTS

              kubetest2 tf --powervs-region ${BOSKOS_REGION} --powervs-zone ${BOSKOS_ZONE} \
                --powervs-service-id ${BOSKOS_RESOURCE_ID} \
                --ignore-cluster-dir true \
                --cluster-name $CLUSTER_NAME\
                --down --auto-approve --ignore-destroy-errors
              [ -z "${BOSKOS_HOST:-}" ] || release_account >> "$ARTIFACTS/boskos.log" 2>&1
              [ $rc != 0 ] && echo "ERROR: E2ENode Test suite exited with code:$rc"; exit $rc
  - name: ci-kubernetes-ppc64le-e2e-alpha-enabled-default
    interval: 6h
    cluster: k8s-infra-ppc64le-prow-build
    labels:
      preset-ibmcloud-cred: "true"
    decorate: true
    decoration_config:
      timeout: 2h
    extra_refs:
      - base_ref: main
        org: kubernetes-sigs
        repo: provider-ibmcloud-test-infra
        workdir: true
    annotations:
      description: Runs e2e tests with alpha enabled feature gates against kubernetes ci latest on IBM powervs
      testgrid-dashboards: ibm-ppc64le-e2e, ibm-ppc64le-k8s, ibm-k8s-e2e
      testgrid-tab-name: ci-kubernetes-ppc64le-e2e-alpha-enabled-default
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20250904-2613a23300-master
          securityContext:
            privileged: true
          env:
            - name: "BOSKOS_HOST"
              value: "boskos.test-pods.svc.cluster.local"
            - name: "USER"
              value: "ci-kubernetes-ppc64le-e2e-alpha-enabled-default"
          resources:
            requests:
              cpu: 2
              memory: "6Gi"
            limits:
              cpu: 2
              memory: "6Gi"
          command:
            - runner.sh
          args:
            - bash
            - -c
            - |
              set -o xtrace

              #Call to boskos to checkout resource
              source "./hack/boskos.sh"

              #Setup of kubetest2 tf deployer and ginkgo tester
              make install-deployer-tf
              go install sigs.k8s.io/kubetest2/kubetest2-tester-ginkgo@latest

              set +o errexit
              set -o xtrace
              kubetest2 tf --powervs-image-name CentOS-Stream-10 --powervs-memory 32 \
                --powervs-region ${BOSKOS_REGION} --powervs-zone ${BOSKOS_ZONE} \
                --powervs-service-id ${BOSKOS_RESOURCE_ID} --powervs-ssh-key k8s-prow-sshkey \
                --ssh-private-key /etc/secret-volume/ssh-privatekey \
                --workers-count 2 --cluster-name alpha-enabled-$(date +%s) \
                --up --down --auto-approve --retry-on-tf-failure 3 --ignore-destroy-errors \
                --break-kubetest-on-upfail true \
                --extra-vars=feature_gates:AllAlpha=true,EventedPLEG=false \
                --extra-vars=runtime_config:api/all=true \
                --build-version $(curl -Ls https://dl.k8s.io/ci/latest.txt) \
                --test=ginkgo -- --parallel 25 --test-package-dir ci --test-package-marker latest.txt \
                --skip-regex="\[Driver:.gcepd\]|\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|KubeProxy.should.update.metric"; rc=$?

              [ -z "${BOSKOS_HOST:-}" ] || release_account >> "$ARTIFACTS/boskos.log" 2>&1
              [ $rc != 0 ] && echo "ERROR: alpha-enabled-default tests exited with code: $rc"; exit $rc
  - name: ci-kubernetes-e2e-ppc64le-default
    interval: 8h
    cluster: k8s-infra-ppc64le-prow-build
    labels:
      preset-ibmcloud-cred: "true"
    decorate: true
    decoration_config:
      timeout: 3h
    extra_refs:
      - base_ref: main
        org: kubernetes-sigs
        repo: provider-ibmcloud-test-infra
        workdir: true
    annotations:
      description: Runs e2e tests with against kubernetes ci latest on IBM powervs
      testgrid-dashboards: ibm-ppc64le-e2e, ibm-ppc64le-k8s, ibm-k8s-e2e
      testgrid-tab-name: ci-kubernetes-e2e-ppc64le-default
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20250904-2613a23300-master
          env:
            - name: "BOSKOS_HOST"
              value: "boskos.test-pods.svc.cluster.local"
            - name: "USER"
              value: "ci-kubernetes-ppc64le-e2e-default"
          resources:
            requests:
              cpu: 2
              memory: "6Gi"
            limits:
              cpu: 2
              memory: "6Gi"
          command:
            - runner.sh
          args:
            - bash
            - -c
            - |
              set -o xtrace

              #Call to boskos to checkout resource
              source "./hack/boskos.sh"

              #Setup of kubetest2 tf deployer and ginkgo tester
              make install-deployer-tf
              go install sigs.k8s.io/kubetest2/kubetest2-tester-ginkgo@latest

              set +o errexit
              set -o xtrace
              kubetest2 tf --powervs-image-name CentOS-Stream-10 --powervs-memory 32 \
                --powervs-region ${BOSKOS_REGION} --powervs-zone ${BOSKOS_ZONE} \
                --powervs-service-id ${BOSKOS_RESOURCE_ID} --powervs-ssh-key k8s-prow-sshkey \
                --ssh-private-key /etc/secret-volume/ssh-privatekey \
                --workers-count 2 --cluster-name e2e-default-$(date +%s) \
                --up --down --auto-approve --retry-on-tf-failure 3 --ignore-destroy-errors \
                --break-kubetest-on-upfail true \
                --build-version $(curl -Ls https://dl.k8s.io/ci/latest.txt) \
                --test=ginkgo -- --parallel 25 --test-package-dir ci --test-package-marker latest.txt \
                --skip-regex="\[Driver:.gcepd\]|\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|KubeProxy.should.update.metric"; rc=$?

              [ -z "${BOSKOS_HOST:-}" ] || release_account >> "$ARTIFACTS/boskos.log" 2>&1
              [ $rc != 0 ] && echo "ERROR: E2e default tests exited with code: $rc"; exit $rc
  - name: ci-kubernetes-ppc64le-e2e-slow-kubetest2
    interval: 3h
    cluster: k8s-infra-ppc64le-prow-build
    labels:
      preset-ibmcloud-cred: "true"
    decorate: true
    decoration_config:
      timeout: 220m
    extra_refs:
      - base_ref: main
        org: kubernetes-sigs
        repo: provider-ibmcloud-test-infra
        workdir: true
    annotations:
      description: Runs E2E slow tests using kubetest2 against kubernetes ci latest on IBM powervs
      testgrid-dashboards: ibm-ppc64le-e2e, ibm-ppc64le-k8s, ibm-k8s-e2e
      testgrid-tab-name: ci-kubernetes-ppc64le-e2e-slow-kubetest2
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20250904-2613a23300-master
          securityContext:
            privileged: true
          env:
            - name: "BOSKOS_HOST"
              value: "boskos.test-pods.svc.cluster.local"
            - name: "USER"
              value: "ci-kubernetes-ppc64le-e2e-slow-kubetest2"
          resources:
            requests:
              cpu: 1
              memory: "6Gi"
            limits:
              cpu: 1
              memory: "6Gi"
          command:
            - runner.sh
          args:
            - bash
            - -c
            - |
              set -o xtrace

              #Call to boskos to checkout resource
              source "./hack/boskos.sh"

              #Setup of kubetest2 tf deployer and ginkgo tester
              make install-deployer-tf
              go install sigs.k8s.io/kubetest2/kubetest2-tester-ginkgo@latest

              set +o errexit
              set -o xtrace
              kubetest2 tf --powervs-image-name CentOS-Stream-10 --powervs-memory 32 \
                --powervs-region ${BOSKOS_REGION} --powervs-zone ${BOSKOS_ZONE} \
                --powervs-service-id ${BOSKOS_RESOURCE_ID} --powervs-ssh-key k8s-prow-sshkey \
                --ssh-private-key /etc/secret-volume/ssh-privatekey \
                --workers-count 2 --cluster-name e2e-slow-$(date +%s) \
                --up --down --auto-approve --retry-on-tf-failure 3 --ignore-destroy-errors\
                --break-kubetest-on-upfail true \
                --build-version $(curl -Ls https://dl.k8s.io/ci/latest.txt) \
                --test=ginkgo -- --parallel 30 --test-package-dir ci --test-package-marker latest.txt --focus-regex='\[Slow\]' --skip-regex='\[Driver:.gcepd\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:' ; rc=$?

              [ -z "${BOSKOS_HOST:-}" ] || release_account >> "$ARTIFACTS/boskos.log" 2>&1
              [ $rc != 0 ] && echo "ERROR: E2e Slow tests exited with code: $rc"; exit $rc
  - name: ci-kubernetes-e2e-ppc64le-serial-kubetest2
    interval: 8h
    cluster: k8s-infra-ppc64le-prow-build
    labels:
      preset-ibmcloud-cred: "true"
    decorate: true
    decoration_config:
      timeout: 3h
    extra_refs:
      - base_ref: main
        org: kubernetes-sigs
        repo: provider-ibmcloud-test-infra
        workdir: true
    annotations:
      description: Runs E2E serial tests using kubetest2 against kubernetes ci latest on IBM powervs
      testgrid-dashboards: ibm-ppc64le-e2e, ibm-ppc64le-k8s, ibm-k8s-e2e
      testgrid-tab-name: ci-kubernetes-e2e-ppc64le-serial-kubetest2
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20250904-2613a23300-master
          env:
            - name: "BOSKOS_HOST"
              value: "boskos.test-pods.svc.cluster.local"
            - name: "USER"
              value: "ci-kubernetes-e2e-ppc64le-serial-kubetest2"
          resources:
            requests:
              cpu: 4
              memory: "14Gi"
            limits:
              cpu: 4
              memory: "14Gi"
          command:
            - runner.sh
          args:
            - bash
            - -c
            - |
              set -o xtrace

              #Call to boskos to checkout resource
              source "./hack/boskos.sh"

              #Setup of kubetest2 tf deployer and ginkgo tester
              make install-deployer-tf
              go install sigs.k8s.io/kubetest2/kubetest2-tester-ginkgo@latest

              set +o errexit
              set -o xtrace
              kubetest2 tf --powervs-image-name CentOS-Stream-10 --powervs-memory 32 \
                --powervs-region ${BOSKOS_REGION} --powervs-zone ${BOSKOS_ZONE} \
                --powervs-service-id ${BOSKOS_RESOURCE_ID} --powervs-ssh-key k8s-prow-sshkey \
                --ssh-private-key /etc/secret-volume/ssh-privatekey \
                --workers-count 2 --cluster-name e2e-serial-$(date +%s) \
                --up --down --auto-approve --retry-on-tf-failure 3 --ignore-destroy-errors\
                --break-kubetest-on-upfail true \
                --extra-vars=container_runtime_test_handler:true \
                --build-version $(curl -Ls https://dl.k8s.io/ci/latest.txt) \
                --test=ginkgo -- --parallel 1 --test-package-dir ci --test-package-marker latest.txt \
                --focus-regex='\[Serial\]|\[Disruptive\]' --skip-regex='\[Driver:.gcepd\]|\[Flaky\]|\[Feature:.+\]|\[sig-cloud-provider-gcp\]'; rc=$?

              [ -z "${BOSKOS_HOST:-}" ] || release_account >> "$ARTIFACTS/boskos.log" 2>&1
              [ $rc != 0 ] && echo "ERROR: E2e Serial tests exited with code: $rc"; exit $rc
