presubmits:
  kubernetes/kubernetes:
  - name: pull-kubernetes-integration-s390x
    cluster: k8s-infra-s390x-prow-build
    always_run: false
    optional: true
    decorate: true
    skip_branches:
    - release-\d+.\d+ # per-release job
    annotations:
      testgrid-dashboards: ibm-s390x-presubmits
    path_alias: k8s.io/kubernetes
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20251021-e2c2c9806f-master
        command:
        - runner.sh
        args:
        - ./hack/jenkins/test-integration-dockerized.sh
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 7
            memory: 20Gi
          requests:
            cpu: 7
            memory: 20Gi
