images:
  cos:
    image_family: cos-117-lts # Use cos-117-lts to lock down what COS version is used with containerd 1.7, which aligns with COS's built-in containerd version
    project: cos-cloud
    metadata: "user-data</home/prow/go/src/github.com/containerd/containerd/test/e2e_node/init.yaml,containerd-configure-sh</home/prow/go/src/github.com/containerd/containerd/cluster/gce/configure.sh,containerd-extra-init-sh</home/prow/go/src/github.com/containerd/containerd/test/e2e_node/gci-init.sh,containerd-env</home/prow/go/src/k8s.io/test-infra/jobs/e2e_node/containerd/containerd-release-1.7-presubmit/env,gci-update-strategy=update_disabled"
