presubmits:
  kubernetes/ingress-nginx:
    # Ingress NGINX: Boilerplate
    - name: pre-ingress-nginx-boilerplate
      labels:
        preset-dind-enabled: "true"
        preset-kind-volume-mounts: "true"
      annotations:
        testgrid-dashboards: sig-network-ingress-nginx
        testgrid-tab-name: boilerplate
      run_if_changed: '\.go$|\.sh$'
      cluster: eks-prow-build-cluster
      decorate: true
      decoration_config:
        timeout: 15m
      path_alias: k8s.io/ingress-nginx
      spec:
        containers:
          - image: registry.k8s.io/ingress-nginx/e2e-test-runner:v20230907-5bb82dcb7@sha256:421cda0f65a949b8b67b5e62a45071702d19ed458a3e2ba753171b0e66943210
            command:
              - ./hack/verify-boilerplate.sh
            resources:
              limits:
                cpu: 2
                memory: 4Gi
              requests:
                cpu: 2
                memory: 4Gi

    # Ingress NGINX: CodeGen
    - name: pre-ingress-nginx-codegen
      labels:
        preset-dind-enabled: "true"
        preset-kind-volume-mounts: "true"
      annotations:
        testgrid-dashboards: sig-network-ingress-nginx
        testgrid-tab-name: codegen
      run_if_changed: '\.go$'
      cluster: eks-prow-build-cluster
      decorate: true
      decoration_config:
        timeout: 15m
      path_alias: k8s.io/ingress-nginx
      spec:
        containers:
          - image: registry.k8s.io/ingress-nginx/e2e-test-runner:v20230907-5bb82dcb7@sha256:421cda0f65a949b8b67b5e62a45071702d19ed458a3e2ba753171b0e66943210
            command:
              - ./hack/verify-codegen.sh
            resources:
              limits:
                cpu: 2
                memory: 4Gi
              requests:
                cpu: 2
                memory: 4Gi

    # Ingress NGINX: Lua Test
    - name: pre-ingress-nginx-lua-test
      labels:
        preset-dind-enabled: "true"
        preset-kind-volume-mounts: "true"
      annotations:
        testgrid-dashboards: sig-network-ingress-nginx
        testgrid-tab-name: test-lua
      run_if_changed: '\.lua$'
      always_run: false
      cluster: eks-prow-build-cluster
      decorate: true
      decoration_config:
        timeout: 10m
      path_alias: k8s.io/ingress-nginx
      spec:
        containers:
          - image: registry.k8s.io/ingress-nginx/e2e-test-runner:v20230907-5bb82dcb7@sha256:421cda0f65a949b8b67b5e62a45071702d19ed458a3e2ba753171b0e66943210
            command:
              - make
              - lua-test
            resources:
              limits:
                cpu: 2
                memory: 4Gi
              requests:
                cpu: 2
                memory: 4Gi
