presubmits:
  kubernetes/ingress-nginx:
    # Ingress NGINX: Boilerplate
    - name: pre-ingress-nginx-boilerplate
      labels:
        preset-dind-enabled: "true"
        preset-kind-volume-mounts: "true"
      annotations:
        testgrid-dashboards: sig-network-ingress-nginx
        testgrid-tab-name: boilerplate
      run_if_changed: \.(go|sh)$
      cluster: eks-prow-build-cluster
      decorate: true
      path_alias: k8s.io/ingress-nginx
      spec:
        containers:
          - image: registry.k8s.io/ingress-nginx/e2e-test-runner:v2.2.1@sha256:8407e6ccec478e9791267657995ee7a021385c52d8f79ea0e6aa4461742ecd21
            command:
              - hack/verify-boilerplate.sh
            resources:
              requests:
                cpu: 2
                memory: 4Gi
              limits:
                cpu: 2
                memory: 4Gi

    # Ingress NGINX: CodeGen
    - name: pre-ingress-nginx-codegen
      labels:
        preset-dind-enabled: "true"
        preset-kind-volume-mounts: "true"
      annotations:
        testgrid-dashboards: sig-network-ingress-nginx
        testgrid-tab-name: codegen
      run_if_changed: \.go$
      cluster: eks-prow-build-cluster
      decorate: true
      path_alias: k8s.io/ingress-nginx
      spec:
        containers:
          - image: registry.k8s.io/ingress-nginx/e2e-test-runner:v2.2.1@sha256:8407e6ccec478e9791267657995ee7a021385c52d8f79ea0e6aa4461742ecd21
            command:
              - hack/verify-codegen.sh
            resources:
              requests:
                cpu: 2
                memory: 4Gi
              limits:
                cpu: 2
                memory: 4Gi

    # Ingress NGINX: Lua Test
    - name: pre-ingress-nginx-lua-test
      labels:
        preset-dind-enabled: "true"
        preset-kind-volume-mounts: "true"
      annotations:
        testgrid-dashboards: sig-network-ingress-nginx
        testgrid-tab-name: lua-test
      run_if_changed: \.lua$
      cluster: eks-prow-build-cluster
      decorate: true
      path_alias: k8s.io/ingress-nginx
      spec:
        containers:
          - image: registry.k8s.io/ingress-nginx/e2e-test-runner:v2.2.1@sha256:8407e6ccec478e9791267657995ee7a021385c52d8f79ea0e6aa4461742ecd21
            command:
              - make
            args:
              - lua-test
            resources:
              requests:
                cpu: 2
                memory: 4Gi
              limits:
                cpu: 2
                memory: 4Gi
