periodics:
- name: periodic-cluster-api-provider-ibmcloud-coverage
  cluster: eks-prow-build-cluster
  interval: 12h
  decorate: true
  annotations:
    testgrid-dashboards: ibm-ppc64le-periodics, ibm-cluster-api
    testgrid-tab-name: periodic-cluster-api-provider-ibmcloud-coverage
  extra_refs:
    - org: kubernetes-sigs
      repo: cluster-api-provider-ibmcloud
      base_ref: main
      path_alias: "sigs.k8s.io/cluster-api-provider-ibmcloud"
    - org: kubernetes
      repo: test-infra
      base_ref: master
      path_alias: k8s.io/test-infra
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20241021-1164926229-1.27
      command:
        - runner.sh
      args:
        - bash
        - -c
        - |
          result=0
          ./scripts/ci-test-coverage.sh || result=$?
          cp cover.* ${ARTIFACTS}
          cd ../../k8s.io/test-infra/gopherage
          GO111MODULE=on go build .
          ./gopherage filter --exclude-path="zz_generated,generated\.go" "${ARTIFACTS}/cover.out" > "${ARTIFACTS}/filtered.cov" || result=$?
          ./gopherage html "${ARTIFACTS}/filtered.cov" > "${ARTIFACTS}/coverage.html" || result=$?
          ./gopherage junit --threshold 0 "${ARTIFACTS}/filtered.cov" > "${ARTIFACTS}/junit_coverage.xml" || result=$?
          exit $result
      resources:
        limits:
          cpu: "2"
          memory: "6Gi"
        requests:
          cpu: "2"
          memory: "6Gi"
- name: periodic-cluster-api-provider-ibmcloud-e2e-powervs
  interval: 8h
  cluster: k8s-infra-ppc64le-prow-build
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-ibmcloud-apikey: "true"
  decorate: true
  decoration_config:
    timeout: 12h
  extra_refs:
    - base_ref: main
      org: kubernetes-sigs
      repo: cluster-api-provider-ibmcloud
      workdir: true
  annotations:
    description: Runs cluster-api-provider-ibmcloud E2E tests against kubernetes cluster on IBM powervs
    testgrid-dashboards: ibm-ppc64le-periodics, ibm-cluster-api
    testgrid-tab-name: periodic-cluster-api-provider-ibmcloud-e2e-powervs
  spec:
    containers:
      - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20250904-2613a23300-master
        env:
          - name: "BOSKOS_HOST"
            value: "boskos.test-pods.svc.cluster.local"
          - name: "RESOURCE_TYPE"
            value: "powervs"
          - name: "USER"
            value: "periodic-cluster-api-provider-ibmcloud-e2e-powervs"
          - name: "E2E_FLAVOR"
            value: "powervs-md-remediation"
          - name: "CUSTOM_KIND_NODE_IMAGE"
            value: "quay.io/powercloud/kind-node:v1.33.4"
        resources:
          requests:
            cpu: 1
          limits:
            cpu: 1
        command:
          - "runner.sh"
          - "./scripts/ci-e2e.sh"
        securityContext:
          privileged: true
