presubmits:
  kubernetes-csi/csi-driver-smb:
  - name: pull-csi-driver-smb-verify
    cluster: k8s-infra-prow-build
    decorate: true
    always_run: true
    path_alias: github.com/kubernetes-csi/csi-driver-smb
    branches:
    - (master)|(^release-.+$)
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240803-cf1183f2db-master
        command:
        - runner.sh
        args:
        - make
        - verify
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "9Gi"
            cpu: 4
          limits:
            memory: "9Gi"
            cpu: 4
    annotations:
      testgrid-dashboards: sig-storage-csi-other
      testgrid-tab-name: pull-csi-driver-smb-verify
      description: "Run code verification tests for SMB CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-csi-driver-smb-unit
    cluster: k8s-infra-prow-build
    decorate: true
    skip_if_only_changed: "^docs/|^site/|^\\.github/|\\.(md|adoc)$|^(README|LICENSE)$"
    path_alias: github.com/kubernetes-csi/csi-driver-smb
    branches:
    - (master)|(^release-.+$)
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240803-cf1183f2db-master
        command:
        - runner.sh
        args:
        - make
        - unit-test
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "9Gi"
            cpu: 4
          limits:
            memory: "9Gi"
            cpu: 4
    annotations:
      testgrid-dashboards: sig-storage-csi-other
      testgrid-tab-name: pull-csi-driver-smb-unit
      description: "Run unit tests for SMB CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-csi-driver-smb-windows-build
    cluster: k8s-infra-prow-build
    decorate: true
    skip_if_only_changed: "^docs/|^site/|^\\.github/|\\.(md|adoc)$|^(README|LICENSE)$"
    path_alias: github.com/kubernetes-csi/csi-driver-smb
    branches:
    - (master)|(^release-.+$)
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240803-cf1183f2db-master
        command:
        - runner.sh
        args:
        - make
        - smb-windows
        resources:
          requests:
            memory: "9Gi"
            cpu: 4
          limits:
            memory: "9Gi"
            cpu: 4
    annotations:
      testgrid-dashboards: sig-storage-csi-other
      testgrid-tab-name: pull-csi-driver-smb-windows-build
      description: "Run make smb-windows for SMB CSI driver."
      testgrid-num-columns-recent: '30'
