postsubmits:
  kubernetes-sigs/node-feature-discovery:
  - name: postsubmit-node-feature-discovery-verify-master
    cluster: eks-prow-build-cluster
    branches:
    - ^main$
    - ^master
    decorate: true
    annotations:
      testgrid-dashboards: sig-node-node-feature-discovery
      testgrid-tab-name: post-verify-master
      description: "Run linters and unit tests"
      testgrid-alert-email: markus.lehtonen@intel.com,feruzjon.muyassarov@intel.com
    spec:
      containers:
      - image: public.ecr.aws/docker/library/golang:1.22
        command:
        - scripts/test-infra/verify.sh
        env:
        - name: CODECOV_TOKEN
          valueFrom:
            secretKeyRef:
              name: nfd-creds
              key: codecov-token
        resources:
          limits:
            cpu: 4
            memory: 8Gi
          requests:
            cpu: 4
            memory: 8Gi
  - name: postsubmit-node-feature-discovery-e2e-test
    cluster: eks-prow-build-cluster
    branches:
    - ^main$
    - ^master$
    labels:
      preset-dind-enabled: "true"
    decorate: true
    annotations:
      testgrid-dashboards: sig-node-node-feature-discovery
      testgrid-tab-name: e2e-test-image
      description: "Run end-to-end tests for node-feature-discovery after merging a pull request"
      testgrid-alert-email: markus.lehtonen@intel.com,feruzjon.muyassarov@intel.com
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240705-131cd74733-master
        # Need privileged mode for dind
        securityContext:
          privileged: true
        command:
        - runner.sh
        args:
        - scripts/test-infra/test-e2e.sh
        resources:
          limits:
            cpu: 6
            memory: 12Gi
          requests:
            cpu: 6
            memory: 12Gi
