presubmits:
  kubernetes-sigs/kubebuilder-declarative-pattern:
  - name: pull-declarative-test
    cluster: eks-prow-build-cluster
    decorate: true
    path_alias: sigs.k8s.io/kubebuilder-declarative-pattern
    always_run: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20251021-e2c2c9806f-master
        command:
        - "./hack/ci/test.sh"
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi
