presubmits:
  kubernetes/minikube:
  - name: pull-minikube-build
    cluster: k8s-infra-prow-build
    decorate: true
    path_alias: "k8s.io/minikube"
    always_run: true
    labels:
      preset-dind-enabled: "true"
    annotations:
      testgrid-dashboards: minikube-presubmits
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20250905-c89b045f57-master
        # we add --force since minikube is running as root
        command:
        - runner.sh
        args:
        - bash
        - -c
        - make && ./out/minikube start --force-systemd --force && kubectl get pods -A
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "2000Mi"
            cpu: 2
          limits:
            memory: "2000Mi"
            cpu: 2
  - name: pull-minikube-integration
    cluster: k8s-infra-prow-build
    decorate: true
    path_alias: "k8s.io/minikube"
    always_run: true
    labels:
      preset-dind-enabled: "true"
    annotations:
      testgrid-dashboards: minikube-presubmits
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20250905-c89b045f57-master
        # we add --force since minikube is running as root
        command:
        - runner.sh
        args:
        - make
        - integration-kvm-prow
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            memory: 20Gi
            cpu: 7
          limits:
            memory: 20Gi
            cpu: 7
