# To copy an image between projects:
# `gcloud compute --project <to-project> disks create <image name> --image=https://www.googleapis.com/compute/v1/projects/<from-project>/global/images/<image-name>`
# `gcloud compute --project <to-project> images create <image-name> --source-disk=<image-name>`
images:
  ubuntu:
    image_family: pipeline-1-29
    project: ubuntu-os-gke-cloud
    # the image regex is added so that only cgroupv2 images are selected.
    # currently all images with cgroupv1 from gke have a -cgroupsv1 suffix
    image_regex: ".*[^-cgroupsv1]$"
    # Using `e2-standard-4` to enable CPU manager node e2e tests.
    machine: e2-standard-4
  cos:
    image_family: cos-125-lts # keep in sync with jobs/e2e_node/containerd/image-config.yaml
    project: cos-cloud
    metadata: "user-data<test/e2e_node/jenkins/cos-init-live-restore.yaml,gci-update-strategy=update_disabled"
    # Using `e2-standard-4` to enable CPU manager node e2e tests.
    machine: e2-standard-4
