presubmits:
  kubernetes/sig-security:
  - name: pull-sig-security-cve-feed-unit-tests
    cluster: eks-prow-build-cluster
    annotations:
      testgrid-dashboards: sig-security-cve-feed
      testgrid-create-test-group: "true"
      description: Running the CVE feed unit tests on each PRs touching the scripts
    run_if_changed: "^sig-security-tooling/cve-feed/hack/"
    branches:
    - main
    decorate: true
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20250902-2613a23300-master
        command: ['runner.sh']
        args: ['python', 'sig-security-tooling/cve-feed/hack/test_cve_title_parser.py', '-v']
        resources:
          limits:
            cpu: 1
            memory: "256m"
          requests:
            cpu: 1
            memory: "256m"
