presets:
- labels:
    preset-gcve-e2e-config: "true"
  env:
  - name: BOSKOS_HOST
    value: http://boskos.test-pods.svc.cluster.local
  - name: GOVC_URL
    valueFrom:
      secretKeyRef:
        name: cluster-api-provider-vsphere-ci
        key: k8s-gcp-gcve-ci-url
  - name: GOVC_USERNAME
    valueFrom:
      secretKeyRef:
        name: cluster-api-provider-vsphere-ci
        key: k8s-gcp-gcve-ci-username
  - name: GOVC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: cluster-api-provider-vsphere-ci
        key: k8s-gcp-gcve-ci-password
  - name: VSPHERE_TLS_THUMBPRINT
    valueFrom:
      secretKeyRef:
        name: cluster-api-provider-vsphere-ci
        key: k8s-gcp-gcve-ci-thumbprint
