periodics:
  - name: periodic-cluster-api-provider-vsphere-e2e-main
    labels:
      preset-dind-enabled: "true"
      preset-cluster-api-provider-vsphere-e2e-config: "true"
      preset-cluster-api-provider-vsphere-gcs-creds: "true"
      preset-kind-volume-mounts: "true"
    decorate: true
    rerun_auth_config:
      github_team_slugs:
      - org: kubernetes-sigs
        slug: cluster-api-provider-vsphere-maintainers
    interval: 24h
    extra_refs:
      - org: kubernetes-sigs
        repo: cluster-api-provider-vsphere
        base_ref: main
        path_alias: sigs.k8s.io/cluster-api-provider-vsphere
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230727-ea685f8747-1.27
          command:
            - runner.sh
          args:
            - ./hack/e2e.sh
          env:
            - name: GINKGO_SKIP
              value: "\\[Conformance\\] \\[clusterctl-Upgrade\\] \\[specialized-infra\\]"
          # we need privileged mode in order to do docker in docker
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
          resources:
            requests:
              cpu: "4000m"
              memory: "6Gi"
    annotations:
      testgrid-dashboards: vmware-cluster-api-provider-vsphere, sig-cluster-lifecycle-cluster-api-provider-vsphere
      testgrid-tab-name: periodic-e2e-main
      testgrid-alert-email: sig-cluster-lifecycle-cluster-api-vsphere-alerts@kubernetes.io
      testgrid-num-failures-to-alert: "4"
      description: Runs all the e2e tests

  - name: periodic-cluster-api-provider-vsphere-conformance-main
    labels:
      preset-dind-enabled: "true"
      preset-cluster-api-provider-vsphere-e2e-config: "true"
      preset-cluster-api-provider-vsphere-gcs-creds: "true"
      preset-kind-volume-mounts: "true"
    decorate: true
    rerun_auth_config:
      github_team_slugs:
      - org: kubernetes-sigs
        slug: cluster-api-provider-vsphere-maintainers
    interval: 24h
    extra_refs:
      - org: kubernetes-sigs
        repo: cluster-api-provider-vsphere
        base_ref: main
        path_alias: sigs.k8s.io/cluster-api-provider-vsphere
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230727-ea685f8747-1.27
          command:
            - runner.sh
          args:
            - ./hack/e2e.sh
          env:
            - name: GINKGO_FOCUS
              value: "\\[Conformance\\]"
          # we need privileged mode in order to do docker in docker
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
          resources:
            requests:
              cpu: "4000m"
              memory: "6Gi"
    annotations:
      testgrid-dashboards: vmware-cluster-api-provider-vsphere, sig-cluster-lifecycle-cluster-api-provider-vsphere
      testgrid-tab-name: periodic-conformance-main
      testgrid-alert-email: sig-cluster-lifecycle-cluster-api-vsphere-alerts@kubernetes.io
      testgrid-num-failures-to-alert: "4"
      description: Runs conformance tests for CAPV

  - name: periodic-cluster-api-provider-vsphere-upgrade-main
    labels:
      preset-dind-enabled: "true"
      preset-cluster-api-provider-vsphere-e2e-config: "true"
      preset-cluster-api-provider-vsphere-gcs-creds: "true"
      preset-kind-volume-mounts: "true"
    decorate: true
    rerun_auth_config:
      github_team_slugs:
      - org: kubernetes-sigs
        slug: cluster-api-provider-vsphere-maintainers
    interval: 24h
    extra_refs:
      - org: kubernetes-sigs
        repo: cluster-api-provider-vsphere
        base_ref: main
        path_alias: sigs.k8s.io/cluster-api-provider-vsphere
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230727-ea685f8747-1.27
          command:
            - runner.sh
          args:
            - ./hack/e2e.sh
          env:
            - name: GINKGO_FOCUS
              value: "\\[clusterctl-Upgrade\\]"
          # we need privileged mode in order to do docker in docker
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
          resources:
            requests:
              cpu: "4000m"
              memory: "6Gi"
    annotations:
      testgrid-dashboards: vmware-cluster-api-provider-vsphere, sig-cluster-lifecycle-cluster-api-provider-vsphere
      testgrid-tab-name: periodic-clusterctl-upgrade-main
      testgrid-alert-email: sig-cluster-lifecycle-cluster-api-vsphere-alerts@kubernetes.io
      testgrid-num-failures-to-alert: "4"
      description: Runs clusterctl upgrade tests for CAPV

  - name: periodic-cluster-api-provider-vsphere-coverage
    interval: 24h
    decorate: true
    rerun_auth_config:
      github_team_slugs:
      - org: kubernetes-sigs
        slug: cluster-api-provider-vsphere-maintainers
    path_alias: "sigs.k8s.io/cluster-api-provider-vsphere"
    extra_refs:
      - org: kubernetes-sigs
        repo: cluster-api-provider-vsphere
        base_ref: main
        path_alias: "sigs.k8s.io/cluster-api-provider-vsphere"
      - org: kubernetes
        repo: test-infra
        base_ref: master
        path_alias: k8s.io/test-infra
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230727-ea685f8747-1.27
          command:
            - runner.sh
            - bash
          args:
            - -c
            - |
              result=0
              ./hack/ci-test-coverage.sh || result=$?
              cp coverage.* ${ARTIFACTS}
              cd ../../k8s.io/test-infra/gopherage
              GO111MODULE=on go build .
              ./gopherage filter --exclude-path="zz_generated,generated\.go" "${ARTIFACTS}/coverage.out" > "${ARTIFACTS}/filtered.cov" || result=$?
              ./gopherage html "${ARTIFACTS}/filtered.cov" > "${ARTIFACTS}/coverage.html" || result=$?
              ./gopherage junit --threshold 0 "${ARTIFACTS}/filtered.cov" > "${ARTIFACTS}/junit_coverage.xml" || result=$?
              exit $result
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
          resources:
            requests:
              cpu: "4000m"
              memory: "6Gi"
    annotations:
      testgrid-dashboards: vmware-cluster-api-provider-vsphere, sig-cluster-lifecycle-cluster-api-provider-vsphere
      testgrid-tab-name: periodic-test-coverage
      testgrid-alert-email: sig-cluster-lifecycle-cluster-api-vsphere-alerts@kubernetes.io
      testgrid-num-failures-to-alert: "4"
      description: Shows test coverage for CAPV

  - name: periodic-cluster-api-provider-vsphere-experimental-failure-on-purpose
    interval: 1h
    decorate: true
    rerun_auth_config:
      github_team_slugs:
        - org: kubernetes-sigs
          slug: cluster-api-provider-vsphere-maintainers
    path_alias: "sigs.k8s.io/cluster-api-provider-vsphere"
    extra_refs:
      - org: kubernetes-sigs
        repo: cluster-api-provider-vsphere
        base_ref: main
        path_alias: "sigs.k8s.io/cluster-api-provider-vsphere"
      - org: kubernetes
        repo: test-infra
        base_ref: master
        path_alias: k8s.io/test-infra
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230727-ea685f8747-1.26
          command:
            # This job should fail every time by calling a script which does not exist.
            - does-not-exist.sh
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
          resources:
            requests:
              cpu: "4000m"
              memory: "6Gi"
    annotations:
      testgrid-dashboards: vmware-cluster-api-provider-vsphere, sig-cluster-lifecycle-cluster-api-provider-vsphere
      testgrid-tab-name: periodic-test-experimental-failure-on-purpose
      testgrid-alert-email: sig-cluster-lifecycle-cluster-api-vsphere-alerts@kubernetes.io
      testgrid-num-failures-to-alert: "1"
      description: Should fail to test alert email address
