presets:
- labels:
    preset-gcve-e2e-config: "true"
  env:
  - name: BOSKOS_HOST
    value: http://boskos.test-pods.svc.cluster.local
  - name: GOVC_URL
    valueFrom:
      secretKeyRef:
        name: cluster-api-provider-vsphere-ci
        key: k8s-gcp-gcve-ci-url
  - name: GOVC_USERNAME
    valueFrom:
      secretKeyRef:
        name: cluster-api-provider-vsphere-ci
        key: k8s-gcp-gcve-ci-username
  - name: GOVC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: cluster-api-provider-vsphere-ci
        key: k8s-gcp-gcve-ci-password
  - name: VSPHERE_TLS_THUMBPRINT
    valueFrom:
      secretKeyRef:
        name: cluster-api-provider-vsphere-ci
        key: k8s-gcp-gcve-ci-thumbprint
  - name: VM_SSH_PUB_KEY
    valueFrom:
      secretKeyRef:
        name: cluster-api-provider-vsphere-ci
        key: k8s-gcp-gcve-ci-ssh-pubkey
  volumeMounts:
  - name: k8s-gcp-gcve-ci-ssh-key
    mountPath: /root/ssh/.private-key
  - name: vmc-vpn
    mountPath: /root/.openvpn
  volumes:
  - name: k8s-gcp-gcve-ci-ssh-key
    secret:
      secretName: cluster-api-provider-vsphere-ci
      defaultMode: 256
      items:
      - key: k8s-gcp-gcve-ci-ssh-key
        path: private-key
