periodics:
- interval: 1h
  cluster: k8s-infra-prow-build
  name: ci-kubernetes-e2e-kind
  annotations:
    testgrid-dashboards: sig-release-master-blocking, sig-testing-kind
    testgrid-tab-name: kind-master
    description: Uses kubetest to run e2e tests for on-by-default features against a latest kubernetes master cluster created with sigs.k8s.io/kind
    testgrid-alert-email: bentheelder@google.com,antonio.ojea.garcia@gmail.com,release-team@kubernetes.io
    testgrid-num-columns-recent: '6'
    fork-per-release: "true"
    fork-per-release-periodic-interval: 1h 2h 6h 24h
  labels:
    preset-dind-enabled: "true"
  decorate: true
  decoration_config:
    timeout: 60m
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/krte:v20250815-171060767f-master
      command:
      - wrapper.sh
      - bash
      - -c
      - curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" && e2e-k8s.sh
      env:
      - name: LABEL_FILTER
        value: "Feature: isEmpty && !Slow && !Disruptive && !Flaky"
      - name: PARALLEL
        value: "true"
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        limits:
          memory: 9Gi
          cpu: 7
        requests:
          # these are both a bit below peak usage during build
          # this is mostly for building kubernetes
          memory: 9Gi
          cpu: 7

- interval: 1h
  cluster: k8s-infra-prow-build
  name: ci-kubernetes-e2e-kind-ipv6
  annotations:
    testgrid-dashboards: sig-release-master-blocking, sig-testing-kind
    testgrid-tab-name: kind-ipv6-master
    description: Uses kubetest to run e2e tests for on-by-default features against a latest kubernetes master IPv6 cluster created with sigs.k8s.io/kind
    testgrid-alert-email: bentheelder@google.com,antonio.ojea.garcia@gmail.com,release-team@kubernetes.io
    testgrid-num-columns-recent: '6'
    fork-per-release: "true"
    fork-per-release-periodic-interval: 1h 2h 6h 24h
  labels:
    preset-dind-enabled: "true"
  decorate: true
  decoration_config:
    timeout: 60m
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/krte:v20250815-171060767f-master
      command:
      - wrapper.sh
      - bash
      - -c
      - curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" && e2e-k8s.sh
      env:
      # enable IPV6 in bootstrap image
      - name: DOCKER_IN_DOCKER_IPV6_ENABLED
        value: "true"
      # tell kind CI script to use ipv6
      - name: IP_FAMILY
        value: "ipv6"
      - name: LABEL_FILTER
        value: "Feature: isEmpty && !Slow && !Disruptive && !Flaky"
      - name: PARALLEL
        value: "true"
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        limits:
          memory: 9Gi
          cpu: 7
        requests:
          # these are both a bit below peak usage during build
          # this is mostly for building kubernetes
          memory: 9Gi
          # during the tests more like 3-20m is used
          cpu: 7

- interval: 4h
  cluster: k8s-infra-prow-build
  name: ci-kubernetes-e2e-kind-alpha-features
  annotations:
    testgrid-dashboards: sig-release-master-informing, sig-testing-kind
    testgrid-tab-name: kind-master-alpha
    description: Runs tests with no special requirements other than alpha feature gates in a KinD cluster where alpha feature gates and APIs are enabled.
    testgrid-alert-email: bentheelder@google.com,antonio.ojea.garcia@gmail.com,release-team@kubernetes.io
    testgrid-num-columns-recent: '6'
  labels:
    preset-dind-enabled: "true"
  decorate: true
  decoration_config:
    timeout: 60m
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/krte:v20250815-171060767f-master
      command:
      - wrapper.sh
      - bash
      - -c
      - curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" && e2e-k8s.sh
      env:
      - name: FEATURE_GATES
        value: '{"AllAlpha":true,"EventedPLEG": false}'
      - name: RUNTIME_CONFIG
        value: '{"api/alpha":"true", "api/ga":"true"}'
      - name: LABEL_FILTER
        value: "Feature: isSubsetOf OffByDefault && !BetaOffByDefault && !Deprecated && !Slow && !Disruptive && !Flaky"
      - name: PARALLEL
        value: "true"
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        limits:
          memory: 9Gi
          cpu: 7
        requests:
          # these are both a bit below peak usage during build
          # this is mostly for building kubernetes
          memory: 9Gi
          cpu: 7

- interval: 4h
  cluster: k8s-infra-prow-build
  name: ci-kubernetes-e2e-kind-beta-features
  annotations:
    testgrid-dashboards: sig-release-master-informing, sig-testing-kind
    testgrid-tab-name: kind-master-beta
    description: Runs tests with no special requirements other than beta feature gates in a KinD cluster where beta feature gates and APIs are enabled.
    testgrid-alert-email: bentheelder@google.com,antonio.ojea.garcia@gmail.com,release-team@kubernetes.io
    testgrid-num-columns-recent: '6'
  labels:
    preset-dind-enabled: "true"
  decorate: true
  decoration_config:
    timeout: 60m
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/krte:v20250815-171060767f-master
      command:
      - wrapper.sh
      - bash
      - -c
      - curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" && e2e-k8s.sh
      env:
      - name: FEATURE_GATES
        value: '{"AllBeta":true}'
      - name: RUNTIME_CONFIG
        value: '{"api/beta":"true", "api/ga":"true"}'
      - name: LABEL_FILTER
        value: "Feature: isSubsetOf OffByDefault && !Alpha && !Deprecated && !Slow && !Disruptive && !Flaky"
      - name: PARALLEL
        value: "true"
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        limits:
          memory: 9Gi
          cpu: 7
        requests:
          # these are both a bit below peak usage during build
          # this is mostly for building kubernetes
          memory: 9Gi
          cpu: 7

- interval: 4h
  cluster: k8s-infra-prow-build
  name: ci-kubernetes-e2e-kind-alpha-beta-features
  annotations:
    testgrid-dashboards: sig-release-master-informing, sig-testing-kind
    testgrid-tab-name: kind-master-alpha-beta
    description: Runs tests with no special requirements other than alpha or beta feature gates in a KinD cluster where alpha and beta feature gates and APIs are enabled.
    testgrid-alert-email: bentheelder@google.com,antonio.ojea.garcia@gmail.com,release-team@kubernetes.io
    testgrid-num-columns-recent: '6'
  labels:
    preset-dind-enabled: "true"
  decorate: true
  decoration_config:
    timeout: 60m
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/krte:v20250815-171060767f-master
      command:
      - wrapper.sh
      - bash
      - -c
      - curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" && e2e-k8s.sh
      env:
      - name: FEATURE_GATES
        value: '{"AllAlpha":true,"AllBeta":true,"EventedPLEG": false}'
      - name: RUNTIME_CONFIG
        value: '{"api/all":"true"}'
      - name: LABEL_FILTER
        value: "Feature: isSubsetOf OffByDefault && !Deprecated && !Slow && !Disruptive && !Flaky"
      - name: PARALLEL
        value: "true"
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        limits:
          memory: 9Gi
          cpu: 7
        requests:
          # these are both a bit below peak usage during build
          # this is mostly for building kubernetes
          memory: 9Gi
          cpu: 7

- interval: 24h
  cluster: k8s-infra-prow-build
  name: ci-kubernetes-e2e-kind-rootless
  annotations:
    testgrid-dashboards: sig-testing-kind
    testgrid-tab-name: kind-rootless
    description: Kubernetes in Rootless Docker (in GCE VM)
    # GitHub ID: @AkihiroSuda
    testgrid-alert-email: suda.kyoto@gmail.com
    testgrid-num-columns-recent: '6'
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20250815-171060767f-master
      command:
      - runner.sh
      args:
      - /bin/bash
      - -c
      - |
        set -eux
        # kindinv: Kubernetes in (Rootless) Docker in (GCE) VM
        # See https://github.com/rootless-containers/kubetest2-kindinv
        #
        # GCE VM is used for setting up cgroup v2 and systemd.
        # (k8s-infra-prow-build lacks cgroup v2, and the kubekins-e2e container lacks systemd)
        (cd ; GO111MODULE=on go install github.com/rootless-containers/kubetest2-kindinv@master)
        mkdir -p -m 0700 ~/.ssh
        cp -f "${GCE_SSH_PRIVATE_KEY_FILE}" ~/.ssh/google_compute_engine
        cp -f "${GCE_SSH_PUBLIC_KEY_FILE}" ~/.ssh/google_compute_engine.pub
        exec kubetest2 kindinv \
          --boskos-location=http://boskos.test-pods.svc.cluster.local \
          --gcp-zone=us-central1-b \
          --instance-image=ubuntu-os-cloud/ubuntu-2404-lts-amd64 \
          --instance-type=n2-standard-4 \
          --kind-rootless \
          --user=rootless \
          --build \
          --up \
          --down \
          --test=ginkgo \
          -- \
          --use-built-binaries \
          --focus-regex='\[NodeConformance\]' \
          --skip-regex='\[Environment:NotInUserNS\]|\[Slow\]' \
          --parallel=8
      resources:
        limits:
          memory: 2Gi
          cpu: 2
        requests:
          memory: 2Gi
          cpu: 2
  rerun_auth_config:
    allow_anyone: true
- interval: 24h
  cluster: k8s-infra-prow-build
  name: ci-kubernetes-e2e-kind-arm64
  annotations:
    testgrid-dashboards: sig-testing-kind
    testgrid-tab-name: kind-master-arm64
    description: Runs e2e tests against a latest kubernetes master created with sigs.k8s.io/kind using arm64
    testgrid-alert-email: bentheelder@google.com,antonio.ojea.garcia@gmail.com, davanum@gmail.com
    testgrid-num-columns-recent: '6'
  labels:
    preset-dind-enabled: "true"
  decorate: true
  decoration_config:
    timeout: 60m
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20250904-2613a23300-master
      command:
      - runner.sh
      args:
      - bash
      - -c
      - curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-arm64.tgz | tar xvfz - -C "${PATH%%:*}/" && e2e-k8s.sh
      env:
      - name: LABEL_FILTER
        value: "Feature: isEmpty && !Slow && !Disruptive && !Flaky"
      - name: PARALLEL
        value: "true"
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        limits:
          memory: 9Gi
          cpu: 7
        requests:
          # these are both a bit below peak usage during build
          # this is mostly for building kubernetes
          memory: 9Gi
          cpu: 7
    nodeSelector:
      kubernetes.io/arch: arm64
