# sigs.k8s.io/kindnet presubmits
presubmits:
  kubernetes-sigs/kindnet:
  - name: pull-kindnet-nftables
    cluster: k8s-infra-prow-build
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    always_run: true
    optional: false
    decorate: true
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
    path_alias: sigs.k8s.io/kindnet
    decoration_config:
      timeout: 60m
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/krte:v20251021-e2c2c9806f-master
        env:
        - name: KUBE_PROXY_MODE
          value: "nftables"
        - name: "PARALLEL"
          value: "true"
        - name: LABEL_FILTER
          value: "!Slow && !Disruptive && !Flaky && Feature: containsAny NetworkPolicy"
        - name: SKIP
          value: \[Feature:SCTPConnectivity\]
        command:
        - wrapper.sh
        - bash
        - -c
        - curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" && $GOPATH/src/sigs.k8s.io/kindnet/hack/ci/e2e.sh
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: "4"
            memory: 9000Mi
          requests:
            cpu: "4"
            memory: 9000Mi
    annotations:
      testgrid-dashboards: sig-network-kindnet
      testgrid-tab-name: pull-kindnet conformance, master (dev) [non-serial]
      testgrid-alert-email: bentheelder@google.com,antonio.ojea.garcia@gmail.com
  - name: pull-kindnet-nftables-ipv6
    cluster: k8s-infra-prow-build
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    always_run: true
    optional: false
    decorate: true
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
    path_alias: sigs.k8s.io/kindnet
    decoration_config:
      timeout: 60m
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/krte:v20251021-e2c2c9806f-master
        env:
        # enable IPV6 in bootstrap image
        - name: "DOCKER_IN_DOCKER_IPV6_ENABLED"
          value: "true"
        # tell kind CI script to use ipv6
        - name: "IP_FAMILY"
          value: "ipv6"
        - name: KUBE_PROXY_MODE
          value: "nftables"
        - name: "PARALLEL"
          value: "true"
        - name: LABEL_FILTER
          value: "!Slow && !Disruptive && !Flaky && Feature: containsAny NetworkPolicy"
        - name: SKIP
          value: \[Feature:SCTPConnectivity\]
        command:
        - wrapper.sh
        - bash
        - -c
        - curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" && $GOPATH/src/sigs.k8s.io/kindnet/hack/ci/e2e.sh
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: "4"
            memory: 9000Mi
          requests:
            cpu: "4"
            memory: 9000Mi
    annotations:
      testgrid-dashboards: sig-network-kindnet
      testgrid-tab-name: pull-kindnet-ipv6 conformance, master (dev) [non-serial]
      testgrid-alert-email: bentheelder@google.com,antonio.ojea.garcia@gmail.com
