presubmits:
  kubernetes-sigs/agent-sandbox:
  - name: presubmit-test-autogen-up-to-date
    cluster: eks-prow-build-cluster
    always_run: true
    decorate: true
    labels:
      preset-service-account: 'true'
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20251016-39cf27682d-master
        command:
        - dev/ci/presubmits/test-autogen-up-to-date
        resources:
          limits:
            cpu: 1
            memory: 4Gi
          requests:
            cpu: 1
            memory: 4Gi
    annotations:
      testgrid-dashboards: sig-apps-agent-sandbox
      testgrid-tab-name: presubmit-test-autogen-up-to-date
      description: presubmit-test-autogen-up-to-date
      testgrid-num-columns-recent: '30'
  - name: presubmit-agent-sandbox-unit-test
    cluster: eks-prow-build-cluster
    always_run: true
    decorate: true
    spec:
      containers:
      - image: public.ecr.aws/docker/library/golang:1.24
        command:
        - dev/ci/presubmits/test-unit
        resources:
          requests:
            cpu: 2
            memory: 4Gi
          limits:
            cpu: 2
            memory: 4Gi
    annotations:
      testgrid-dashboards: sig-apps-agent-sandbox
      testgrid-tab-name: presubmit-unit-test
  - name: presubmit-agent-sandbox-lint-go
    cluster: eks-prow-build-cluster
    always_run: true
    decorate: true
    spec:
      containers:
      - image: public.ecr.aws/docker/library/golang:1.24
        command:
        - dev/ci/presubmits/lint-go
        resources:
          requests:
            cpu: 4
            memory: 8Gi
          limits:
            cpu: 4
            memory: 8Gi
    annotations:
      testgrid-dashboards: sig-apps-agent-sandbox
      testgrid-tab-name: presubmit-lint-go
  - name: presubmit-agent-sandbox-e2e-test
    cluster: eks-prow-build-cluster
    always_run: true
    decorate: true
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20251016-39cf27682d-master
        command:
        - runner.sh
        - dev/ci/presubmits/test-e2e
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 7
            memory: 14Gi
          limits:
            cpu: 7
            memory: 14Gi
    annotations:
      testgrid-dashboards: sig-apps-agent-sandbox
      testgrid-tab-name: presubmit-e2e-test
