---
presubmits:
  etcd-io/etcd-operator:
  - name: pull-etcd-operator-test
    cluster: eks-prow-build-cluster
    always_run: true
    branches:
    - main
    decorate: true
    annotations:
      testgrid-dashboards: sig-etcd-operator-presubmits
      testgrid-tab-name: pull-etcd-operator-test
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20250925-95b5a2c7a5-master
        command:
        - runner.sh
        args:
        - bash
        - -c
        - |
          go mod tidy
          make test
        resources:
          requests:
            cpu: "4"
            memory: "4Gi"
          limits:
            cpu: "4"
            memory: "4Gi"
  - name: pull-etcd-operator-test-e2e
    cluster: k8s-infra-prow-build
    always_run: true
    branches:
    - main
    decorate: true
    labels:
      preset-dind-enabled: "true"
    annotations:
      testgrid-dashboards: sig-etcd-operator-presubmits
      testgrid-tab-name: pull-etcd-operator-test-e2e
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/krte:v20250925-95b5a2c7a5-master
        command:
        - wrapper.sh
        args:
        - bash
        - -c
        - |
          make test-e2e
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: "4"
            memory: "4Gi"
          limits:
            cpu: "4"
            memory: "4Gi"
  - name: pull-etcd-operator-verify
    cluster: eks-prow-build-cluster
    always_run: true
    branches:
    - main
    decorate: true
    annotations:
      testgrid-dashboards: sig-etcd-operator-presubmits
      testgrid-tab-name: pull-etcd-operator-verify
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20250925-95b5a2c7a5-master
        command:
        - runner.sh
        args:
        - bash
        - -c
        - make verify
        resources:
          requests:
            cpu: "4"
            memory: "6Gi"
          limits:
            cpu: "4"
            memory: "6Gi"
