---
presubmits:
  etcd-io/protodoc:
    - name: pull-protodoc-test
      cluster: eks-prow-build-cluster
      always_run: true
      branches:
        - master
      decorate: true
      annotations:
        testgrid-dashboards: sig-etcd-protodoc-presubmits
        testgrid-tab-name: pull-protodoc-test
      spec:
        containers:
          - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20251015-a2dc851e09-master
            command:
              - runner.sh
            args: ['make', 'test']
            resources:
              requests:
                cpu: "4"
                memory: "4Gi"
              limits:
                cpu: "4"
                memory: "4Gi"
