postsubmits:
  kubernetes/test-infra:
  - name: post-test-infra-deploy-prow
    cluster: test-infra-trusted
    run_if_changed: '^(config/prow/cluster/|config/prow/Makefile$|Makefile.base.mk$)'
    decorate: true
    branches:
    - ^master$
    max_concurrency: 1
    reporter_config:
      slack:
        channel: "prow-alerts"
        job_states_to_report:
        - success
        - failure
        - aborted
        - error
        report_template: 'Deploying prow: {{.Status.State}}. Commit: <{{.Spec.Refs.BaseLink}}|{{printf "%.7s" .Spec.Refs.BaseSHA}}> | <{{.Status.URL}}|Spyglass> | <https://testgrid.k8s.io/sig-testing-prow#deploy-prow|Testgrid> | <https://prow.k8s.io/?job={{.Spec.Job}}|Deck>'
    spec:
      serviceAccountName: deployer
      containers:
      - image: gcr.io/k8s-staging-test-infra/gcloud-in-go:v20230111-cd1b3caf9c
        command:
        - make
        args:
        - -C
        - config/prow
        - deploy-all
    annotations:
      testgrid-dashboards: sig-testing-prow
      testgrid-tab-name: deploy-prow
      testgrid-alert-email: kubernetes-sig-testing-alerts@googlegroups.com, k8s-infra-oncall@google.com
      testgrid-num-failures-to-alert: '1'
      description: deploys the configured version of prow by running prow/deploy.sh
  - name: post-test-infra-gencred-refresh-kubeconfig
    cluster: test-infra-trusted
    run_if_changed: '^config/prow/gencred-config/'
    decorate: true
    branches:
    - ^master$
    spec:
      serviceAccountName: gencred-refresher
      containers:
      - name: gencred
        image: gcr.io/k8s-staging-test-infra/gencred:v20240801-a5d9345e59
        command:
        - gencred
        args:
        - --config=./config/prow/gencred-config/gencred-config.yaml
    annotations:
      testgrid-num-failures-to-alert: '1'
      testgrid-dashboards: sig-testing-misc
      testgrid-tab-name: postsubmit-gencred-refresh-kubeconfig
      testgrid-alert-email: kubernetes-sig-testing-alerts@googlegroups.com, k8s-infra-oncall@google.com
      description: Runs gencred to refresh generated kubeconfigs.

periodics:
  # Save for standard time:
  # cron: "30 18-23/5 * * 1-5"  # Bump with label `skip-review`. Run at 10:30 and 15:30 PST (18:05 UTC, fall) Mon-Fri
  # Save for daylight savings time:
- cron: "30 17-22/5 * * 1-5"  # Bump with label `skip-review`. Run at 10:30 and 15:30 PST (17:05 UTC, spring) Mon-Fri
  name: ci-test-infra-autobump-prow-for-auto-deploy
  cluster: test-infra-trusted
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: test-infra
    base_ref: master
  spec:
    containers:
    - image: us-docker.pkg.dev/k8s-infra-prow/images/generic-autobumper:v20240802-66b115076
      command:
      - generic-autobumper
      args:
      - --config=config/prow/autobump-config/prow-component-autobump-config.yaml
      - --labels-override=skip-review # This label is used by tide for identifying trusted PR
      - --skip-if-no-oncall # Only apply `skip-review` label when oncall is active
      volumeMounts:
      - name: github
        mountPath: /etc/github-token
        readOnly: true
      - name: ssh
        mountPath: /root/.ssh
    volumes:
    - name: github
      secret:
        secretName: oauth-token
    - name: ssh
      secret:
        secretName: k8s-ci-robot-ssh-keys
        defaultMode: 0400
  annotations:
    testgrid-dashboards: sig-testing-prow
    testgrid-tab-name: autobump-prow-for-auto-deploy
    testgrid-alert-email: k8s-infra-oncall@google.com
    testgrid-num-failures-to-alert: '2' # This could fail when it runs right in the middle of prow push, tolerate it once
    description: runs autobumper to create/update a PR that bumps prow to the latest RC with label 'skip-review'
- cron: "15 * * * 1-5"  # Bump don't label `skip-review`. Run at :30 past every hour Mon-Fri
  name: ci-test-infra-autobump-prow
  cluster: test-infra-trusted
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: test-infra
    base_ref: master
  spec:
    containers:
    - image: us-docker.pkg.dev/k8s-infra-prow/images/generic-autobumper:v20240802-66b115076
      command:
      - generic-autobumper
      args:
      - --config=config/prow/autobump-config/prow-component-autobump-config.yaml
      volumeMounts:
      - name: github
        mountPath: /etc/github-token
        readOnly: true
      - name: ssh
        mountPath: /root/.ssh
    volumes:
    - name: github
      secret:
        secretName: oauth-token
    - name: ssh
      secret:
        secretName: k8s-ci-robot-ssh-keys
        defaultMode: 0400
  annotations:
    testgrid-dashboards: sig-testing-prow
    testgrid-tab-name: autobump-prow
    description: runs autobumper to create/update a PR that bumps prow to the latest RC without label 'skip-review'
    testgrid-alert-email: k8s-infra-oncall@google.com
    testgrid-num-failures-to-alert: '3'
- cron: "17 */6 * * *"  # Every 6 hours at 17 minutes past the hour
  name: ci-test-infra-gencred-refresh-kubeconfig
  cluster: test-infra-trusted
  extra_refs:
  - org: kubernetes
    repo: test-infra
    base_ref: master
  decorate: true
  spec:
    serviceAccountName: gencred-refresher
    containers:
    - name: gencred
      image: gcr.io/k8s-staging-test-infra/gencred:v20240801-a5d9345e59
      command:
      - gencred
      args:
      - --config=./config/prow/gencred-config/gencred-config.yaml
  annotations:
    testgrid-num-failures-to-alert: '6'
    testgrid-alert-stale-results-hours: '12'
    testgrid-dashboards: sig-testing-misc
    testgrid-tab-name: gencred-refresh-kubeconfig
    testgrid-alert-email: kubernetes-sig-testing-alerts@googlegroups.com, k8s-infra-oncall@google.com
    description: Runs gencred to refresh generated kubeconfigs.
