# To copy an image between projects:
# `gcloud compute --project <to-project> disks create <image name> --image=https://www.googleapis.com/compute/v1/projects/<from-project>/global/images/<image-name>`
# `gcloud compute --project <to-project> images create <image-name> --source-disk=<image-name>`
images:
  ubuntu:
    image_family: pipeline-1-34-amd64
    project: ubuntu-os-gke-cloud
    # the image regex is added so that only cgroupv2 images are selected.
    # currently all images with cgroupv1 from gke have a -cgroupsv1 suffix
    image_regex: ".*[^-cgroupsv1]$"
    metadata: "user-data</home/prow/go/src/k8s.io/test-infra/jobs/e2e_node/containerd/ubuntu-init-hugepages-1G-allocation.yaml,cni-template</home/prow/go/src/k8s.io/test-infra/jobs/e2e_node/containerd/cni.template,containerd-config</home/prow/go/src/k8s.io/test-infra/jobs/e2e_node/containerd/config.toml,registry-config-docker</home/prow/go/src/k8s.io/test-infra/jobs/e2e_node/containerd/hosts-docker.toml"
    # Using `e2-standard-2` to have enough memory for 1Gb huge pages allocation
    machine: e2-standard-2
